version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "21:00"
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "21:00"
    open-pull-requests-limit: 20
